##logging:
  ###可选：默认配置logback-spring.xml

server:
  port: 9090

spring:
  application:
    name: eureka-client-service

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:8200/eureka

  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径就会显示成IP地址

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: http://localhost
        allowed-methods: GET,POST

  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true

    # 这里的配置主要是在admin server中看到日志记录
    logfile:
      external-file: G:/logs/eureka-client.2020-09-14.0.log


user:
  username: zhangsan
  password: 123456

