server:
  port: 8080

spring:
  application:
    name: admin-service
  profiles:
    active: secure
  security:
    user:
      name: admin
      password: 123456


eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    registryFetchIntervalSeconds: 5
    serviceUrl: # 注册到哪一个Eureka Server服务注册中心，多个中间用逗号分隔
      defaultZone: http://localhost:8200/eureka/

  instance:
    instanceId: ${spring.application.name}:${server.port}
    prefer-ip-address: true #访问路径就会显示成IP地址


management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: http://localhost
        allowed-methods: GET,POST

  endpoint:
    health:
      show-details: ALWAYS
    shutdown:
      enabled: true







